alias c='clear'
alias sudo='sudo '
alias ls='ls -GF'
alias ll='ls -l'
alias la='ls -a'
alias l='ls -al'
alias md5='md5 -r'
alias md5sum='md5 -r'
alias gvim='open -a /Applications/MacVim.app'
source `brew --prefix`/Library/Contributions/brew_bash_completion.sh
alias cowsay='fortune | cowsay'
alias hide='chflags hidden'
alias show='chflags nohidden'
alias sora='open /Applications/MPlayerX.app ~/Movies/空は高く\ 風は歌う.mkv'
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
alias vibr='gvim /Users/pxs/Software.localized/Github/bashrc/bashrc'
alias vivr='gvim /Users/pxs/Software.localized/Github/vimrc/vimrc'
alias vihosts='gvim /etc/hosts'
